Message.create(content: "Hi, this is Gaben from Valve!")
Message.create(content: "Welcome.")
Message.create(content: "Greetings, traveler!")
Message.create(content: "Axe says good day sir")
Message.create(content: "Hello micronout")